// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0

package models

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Role struct {
	ID          string             `db:"id" json:"id"`
	Name        pgtype.Text        `db:"name" json:"name"`
	DisplayName pgtype.Text        `db:"display_name" json:"display_name"`
	CreatedBy   pgtype.Text        `db:"created_by" json:"created_by"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	DeletedAt   pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
}

type RolePermission struct {
	ID        string             `db:"id" json:"id"`
	RoleID    string             `db:"role_id" json:"role_id"`
	Path      pgtype.Text        `db:"path" json:"path"`
	Name      pgtype.Text        `db:"name" json:"name"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	DeletedAt pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
}

type User struct {
	ID        string             `db:"id" json:"id"`
	Username  pgtype.Text        `db:"username" json:"username"`
	Email     pgtype.Text        `db:"email" json:"email"`
	Password  pgtype.Text        `db:"password" json:"password"`
	RoleID    pgtype.Text        `db:"role_id" json:"role_id"`
	Token     pgtype.Text        `db:"token" json:"token"`
	CreatedBy pgtype.Text        `db:"created_by" json:"created_by"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	DeletedAt pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
}
