// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0

package models

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	GetUser(ctx context.Context, email pgtype.Text) (*User, error)
}

var _ Querier = (*Queries)(nil)
