version: "3.4"

services:
  generate_pb_go:
    image: gen-go
    build:
      context: ../
      target: protoc_gen_go
      dockerfile: ./developments/proto.Dockerfile
    working_dir: /app/
    volumes:
      - "../:/app/"
    entrypoint: bash ./developments/gen_proto.sh

  generate_sqlc:
    image: sqlc/sqlc:1.23.0
    volumes:
      - "../database/postgres:/src/"
      - "../:/app/"
      - "./sqlc.yaml:/sqlc.yaml"
    command: ["generate", "--experimental"]

  postgres:
    container_name: postgres_container
    image: postgres:13-alpine
    environment:
      PGDATA: /data/postgres
      POSTGRES_DB: postgres
      DATABASE_HOST: localhost
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped

  migrate:
    image: migrate/migrate
    env_file:
      - ./.env
    volumes:
      - "../database/postgres/migrations:/migrations/"
    networks:
      - postgres
    command: ["-path", "/migrations", "-database", "${DATABASE_URL}", "up"]

  user_migrate:
    image: migrate/migrate
    env_file:
      - ./.env
    volumes:
      - "../database/postgres/migrations/users:/migrations/"
    networks:
      - postgres
    command: ["-path", "/migrations", "-database", "${DATABASE_URL}", "up"]

  adminer:
    image: adminer
    restart: always
    ports:
      - 3037:8080
    networks:
      - postgres


networks:
  postgres:
    driver: bridge
