version: "3.4"

services:
  generate_pb_go:
    image: gen-go
    build:
      context: ../
      target: protoc_gen_go
      dockerfile: ./developments/proto.Dockerfile
    working_dir: /app/
    volumes:
      - "../:/app/"
    entrypoint: bash ./developments/gen_proto.sh

  generate_sqlc:
    image: sqlc/sqlc:1.23.0
    volumes:
      - "../database/postgres:/src/"
      - "../:/app/"
      - "./sqlc.yaml:/sqlc.yaml"
    command: ["generate", "--experimental"]

  generate_mock:
    image: vektra/mockery
    working_dir: /code
    volumes:
      - "../:/code:cached"

    command: ["--all", "--dir", "internal", "--case", "underscore"]

  generate_contract:
    image: gen-contract
    build:
      context: ../
      target: abi_gen_contract
      dockerfile: ./developments/abi.Dockerfile
    volumes:
      - "../:/app/"
    entrypoint: /app/developments/gen-abi.sh

  postgres:
    container_name: postgres_container
    image: postgres:13-alpine
    environment:
      PGDATA: /data/postgres
      POSTGRES_DB: shopvui
      DATABASE_HOST: localhost
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: shopvui
    ports:
      - "5431:5432"
    networks:
      - postgres
    restart: unless-stopped

  bdd_test:
    container_name: bdd_container
    build:
      context: ../
      dockerfile: ./developments/bdd_test.Dockerfile
    volumes:
      - "../:/app/"
    command: ["godog", "run"]

  migrate:
    image: migrate/migrate
    env_file:
      - ./.env
    volumes:
      - "../database/postgres/migrations:/migrations/"
    networks:
      - postgres
    command: ["-path", "/migrations", "-database", "${DATABASE_URL}", "up"]

  user_migrate:
    image: migrate/migrate
    env_file:
      - ./.env
    volumes:
      - "../database/postgres/migrations/users:/migrations/"
    networks:
      - postgres
    command: ["-path", "/migrations", "-database", "${DATABASE_URL}", "up"]

  adminer:
    image: adminer
    restart: always
    ports:
      - 3037:8080
    networks:
      - postgres

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.0.0
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false

  scylladb:
    image: "scylladb/scylla"
    container_name: scylladb
    restart: always
    ports:
      - 9042:9042
    volumes:
      - SCYLLA_DB:/var/lib/scylla

networks:
  postgres:
    driver: bridge

volumes:
  postgres:
  SCYLLA_DB:
    name: SCYLLA_DB
