/* *
                      _
  ___   _   _   ___  | |_    ___    _ __ ___
 / __| | | | | / __| | __|  / _ \  | '_ ` _ \
| (__  | |_| | \__ \ | |_  | (_) | | | | | | |
 \___|  \__,_| |___/  \__|  \___/  |_| |_| |_|

*/
// * Code generated by protoc-gen-custom. DO NOT EDIT.
// * versions:
// * - protoc-gen-custom (devel)
// * - protoc                   v3.14.0
// * source: pb

package pb

var AllPathToMethodMap = map[string]string{
	UserService_Login_API:       "POST /v1/user/login",
	UserService_Register_API:    "POST /v1/user/register",
	UserService_GetUserByID_API: "GET /v1/user/*",
}

var AllPathToMethodSlice = []string{
	"UserService_Login_API",
	"UserService_Register_API",
	"UserService_GetUserByID_API",
}
