/* *
                      _
  ___   _   _   ___  | |_    ___    _ __ ___
 / __| | | | | / __| | __|  / _ \  | '_ ` _ \
| (__  | |_| | \__ \ | |_  | (_) | | | | | | |
 \___|  \__,_| |___/  \__|  \___/  |_| |_| |_|

*/
// * Code generated by protoc-gen-custom. DO NOT EDIT.
// * versions:
// * - protoc-gen-custom (devel)
// * - protoc                   v3.14.0
// * source: pb

package pb

const (
	UserService_Login       = "/pb.UserService/Login"
	UserService_Register    = "/pb.UserService/Register"
	UserService_GetUserByID = "/pb.UserService/GetUserByID"
)

const (
	UserService_Login_API       = "UserService_Login_API"
	UserService_Register_API    = "UserService_Register_API"
	UserService_GetUserByID_API = "UserService_GetUserByID_API"
)

var UserService_APIs = []string{
	UserService_Login_API,
	UserService_Register_API,
	UserService_GetUserByID_API,
}
