// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0

package models

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Role struct {
	RoleID    string             `db:"role_id" json:"role_id"`
	Name      string             `db:"name" json:"name"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	DeletedAt pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
}

type User struct {
	UserID    string             `db:"user_id" json:"user_id"`
	Email     string             `db:"email" json:"email"`
	Password  string             `db:"password" json:"password"`
	FirstName string             `db:"first_name" json:"first_name"`
	LastName  string             `db:"last_name" json:"last_name"`
	Active    pgtype.Bool        `db:"active" json:"active"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	DeletedAt pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
}

type UserRole struct {
	UserID    string             `db:"user_id" json:"user_id"`
	RoleID    string             `db:"role_id" json:"role_id"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	DeletedAt pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
}
